spring:
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/hsq_query_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 30000
      max-lifetime: 600000
      pool-name: HikariCP
  jpa:
    hibernate:
      ddl-auto: create-drop
      properties:
        hibernate:
          format_sql: true
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: "123456"
    virtual-host: /

broker:
  queue:
    task:
      exchange:
        name: tasks
      created:
        routing-key: tasks.v1.task-created

server:
  port: 8082

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
      cnes-unidade:
        connectTimeout: 2000
        readTimeout: 2000